### PR TITLE
Add photoevaporation modules

### PR DESCRIPTION
**Pull request by AndrewSellek**
Additional external and internal photoevaporation modules and edits to existing modules to work with these. Upgrade of the dust evolution to use the prescription from Dipierro et al. 18 for the dust-gas relative velocity.

### CODE REVIEW

**Comment by rbooth200** [comment]
Hi Andrew, 

Thanks for this. It's an enormous amount of work and the both the history and photoevaporation code will be useful in the future. I would prefer, if possible, to work with you on some changes to how these new features interface with the rest of the code before merging them into master. My motivation is to guard against challenges for future maintenance or extensions of the code as the complexity increases.

The main things I'd like to do are:
1. Extract the history objects from the disc classes and make them their own separate entity.
2. Make the photoevaporation routines more self-contained

The way I'd design the history module is something along the following lines:
```
class History:
    def __init__(self, options):
        # Setup options, initialize history
    def record_state(self, disc):
        # Compute the desired values and store them
    def load(self, filename):
        # Load from file
    def save(self, filename):
        # Save to file
```
Other methods could be added for, e.g. storing the details of the photo-evaporation rates. 

I'd then pass an object of the `History` class to the `driver` object. The driver object would then call the record_state method after each time step. I think that solution offers the most flexibililty - the history classes can be adapted depending the data that is desired. Do you think that would work well? 

I need to think more about the photoevaporation. Essentially I'd like the driver class to not have to worry about details like whether there is a hole or whether the time-step needs to be limited, etc. I.e. I'd like there to be a single class that handles both the cases with and without holes. 

Since these changes might be substantial, it might be best if we provide exactly your implementation with the paper (rather than re-doing everything after modifications).

**Comment by AndrewSellek** [comment]
I think I've made the structural changes you suggested.
The internal photoevaporation module now has one class for a photoevaporating disc. Each prescription (Owen, Picogna, EUV) has its own child class with separate methods for Primordial and InnerHole discs. The class has an attribute to know which is active and checks whether to switch over itself when called.
Many of the actual calculations for the history module I have left in their own module since e.g. there may be other things that would like to know the total mass of the disc and want to call that. But rather than these being passed a variable to tell them whether to save to history, they always return a value. "History" calls these and then stores the value in its own attributes. Various instructions to restart, log values and save have been moved into this module from the run_model.py script. Additionally I added tracking for the cumulative amount of gas removed by a wind due to external photoevaporation, as well as the dust. The history module acts just like the plotting option in terms of the json, with the ability to switch it off entirely, or specific times. 
[Nb in my version of run_model, if the times are set to [0] then it inherits the main output times. To focus the outputs sensibly I often used log-spaced times. If this is set (arrange=log rather than arrange=explicit) it will override the times provided for plotting and history (with warning) so that all 3 coincide. In practice I never use plotting.]

**Review by rbooth200 — APPROVED** [review]

**Comment by rbooth200** [comment]
Thanks for this, it looks great. I need to make some changes to get the FRIED grid to work with my install scripts (which have changed in the last couple of years). Once I've done that, I'll let you know

**Comment by AndrewSellek** [comment]
Sounds great – glad to hear it’s all coming together!

**Comment by rbooth200** [comment]
Do you have time to chat today about the viscous velocity implementation?

**Comment by rbooth200** [comment]
It's ok, I think its fine

**Comment by AndrewSellek** [comment]
Ok, I am free any time between now and 5 if anything else does come up or you want to check the implementation anyway.

Andrew

**Comment by rbooth200** [comment]
Can you try installing my latest version and checking that your internal / external PE results look sensible?

**Comment by rbooth200** [comment]
The only siginificant changes I've made are:
 - h_edge is replaced by an approximation (average / extrapolation)
 - I've update v_visc to be the center of mass velocity (because I think that's what is normally wanted)

**Comment by AndrewSellek** [comment]
Yes I can try this now

**Comment by AndrewSellek** [comment]
On the second of these – the prescription of Dipierro+2018 used 1/rho_g to define their v_visc, so that it corresponds to the velocity of the gas in the limit that there is no coupling - this is why I passed the gas density. But I see you’ve multiplied by 1+eps in the dust module to account for this which is probably a simpler implementation – I wonder if this should be 1/1-eps though?

**Comment by rbooth200** [comment]
I think multiplication is correct. The torques (forces) are the same but the total mass moved is more, so I get a lower velocity. The 1+eps should correct that

**Comment by AndrewSellek** [comment]
I agree that the lower velocity results - my issue is that their v_visc is independent of the normalisation of rho_g so at fixed total rho, as rho_d -> rho_tot, v_visc shouldn’t change, but the actual radial velocity of the gas (their eq 20) does decrease.
From that equation taking St=0 and vp=0 (so everything moves at one speed determined by viscosity as per your argument) and  accounting for their definition of epsilon being different: 1/(1+rho_d/rho_g) = rho_g/rho_tot = (1-eps) -> ur = (1-eps) * v_visc. Hence dividing by (1-eps) (which for smaller eps ~ * (1+eps) ) should also make the velocity lower?

I’ll have to run and check I get sensible results with changing this in the cavity/gap when eps->1.

**Comment by AndrewSellek** [comment]
I think all my tests look sensible.

With regards to the question of the 1+eps factor, I ran the same X-ray disc with my original way of calculating the viscous term, and the change you made. Mostly I don’t think it really gets to the point where eps~1 and these differences would matter except in the gap where there is very little dust anyway and no gas to provide drag/couple to. As the final clearing of the outer disc goes on, eps does start getting larger. Since the dust is trapped anyway it seems to have little effect, but the feedback on the gas is visible – with your implementation the growth of the hole radius is lightly slower which keeps the mass loss rates a bit higher.
These differences might be more important in the case of the debris discs Cathie’s student is going to be working on, so I think it is important that we agree which is right…

Just to let you know I identified a couple of bugs - one which was sometimes stopping the code correctly identifying a hole and another where I hadn’t changed when I reset the hole radii if one that later turns out to not be the correct hole disappears (it sometimes gets confused by the outer disc depending on the interplay between the Sigma and Sigmadot profiles).

I’ll update these on my version and put in a pull request to fix them in your master.

**Comment by rbooth200** [comment]
I see my mistake now, and agree with you that 1+eps should be replaced with 1 / (1-eps). Do you want to make that change.

Thanks for fixing bugs, too.

**Comment by AndrewSellek** [comment]
Ok I'll make that change along with the others. Do you suggest I make the denominator 1+1e-300-eps for stability?

**Comment by rbooth200** [comment]
It might help, was the small number (1e-300) needed in your original implementation?

**Comment by rbooth200** [comment]
You could just use eps_g as already defined in the code instead of 1-eps.sum()

**Comment by AndrewSellek** [comment]
I didn’t need it explicitly because I was passing the gas density which presumably is similarly pinned to a small number.
But yes, this is the most sensible idea I think. I’ll make the change now and test it.

**Comment by AndrewSellek** [comment]
I’m having some issues with this at the moment – when the gas density is sufficiently low in the gap (say eps_g ~ 10^-17) then when the code calculates eps_av, it loses this precision that eps is not quite 1, and return eps_av=1 -> average eps_g=1e-300. This means that the correction factor is a couple of hundred orders of magnitude too high, which leads to insanely high velocities, grinding everything to a halt.
I think if I calculate SigG_av and eps_g explicitly rather than from the dust it ought to eliminate this problem, so I’m going to test that out now.

**Comment by rbooth200** [comment]
That should work since its essentially what you were doing before.

**Comment by AndrewSellek** [comment]
Ok that worked – I’ve put in a new pull request with the edits. I think it’s good we got this right but actually the differences I highlighted before seemed to be arising in the hole identification because it was using the Picogna prescription to clear up anything left in the gap which had an outer edge so lead to a non-contiguous photoevaporating regions – I’m not sure why the bug only showed up when we changed the implementation of the gas velocities but it should all be fixed now.

**Pull request merged**
